/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pappu_com_facedetection_java_jni_Facedetection */

#ifndef _Included_pappu_com_facedetection_java_jni_Facedetection
#define _Included_pappu_com_facedetection_java_jni_Facedetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pappu_com_facedetection_java_jni_Facedetection
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pappu_com_facedetection_java_1jni_Facedetection_initialize
  (JNIEnv *, jobject);

/*
 * Class:     pappu_com_facedetection_java_jni_Facedetection
 * Method:    deserialize
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_pappu_com_facedetection_java_1jni_Facedetection_deserialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     pappu_com_facedetection_java_jni_Facedetection
 * Method:    getFaceRectangle
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_pappu_com_facedetection_java_1jni_Facedetection_getFaceRectangle
  (JNIEnv *, jobject);

/*
 * Class:     pappu_com_facedetection_java_jni_Facedetection
 * Method:    faceDetect
 * Signature: ([BJJIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_pappu_com_facedetection_java_1jni_Facedetection_faceDetect
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
