/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pappu_com_facedetection_java_jni_Facedetection */

#ifndef _Included_pappu_com_facedetection_java_jni_Facedetection
#define _Included_pappu_com_facedetection_java_jni_Facedetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pappu_com_facedetection_java_jni_Facedetection
 * Method:    getid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pappu_com_facedetection_java_1jni_Facedetection_getid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
